project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  search: false
  navbar: false

format:
  html:
    theme: [lux, theme.scss]
    css: styles.css
    include-in-header: Header/header.html



